[package]
name = "currency"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.26"
serde = { version = "1.0.197", features = ["derive"] }
tokio = "1.36.0"
